spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup,paymentGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderConfirmation:com.luxemart.order.OrderConfirmation,paymentConfirmation:com.luxemart.payment.PaymentConfirmation

  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification

  mail:
    host: smtp.gmail.com
    port: 587
    username: jadduravi0@gmail.com
    password: gxgfzsvlgyjraihg
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000


server:
  port: 9995

logging:
  level:
    org:
      springframework:
        mail: DEBUG