spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      properties:
        spring.json.type.mapping: orderConfirmation:com.luxemart.order.OrderConfirmation

server:
  port: 9993

application:
  config:
    customer-url: http://localhost:9991/customer
    product-url: http://localhost:9992/product
    payment-url: http://localhost:9994/payment